version: "2"
services:
  api:
    image: node:16
    container_name: codx-api
    working_dir: /src
    command: bash -c "yarn build && yarn develop"
    volumes:
      - "$CODX_PATH/server:/src"
    restart: unless-stopped
    environment:
      - "NODE_ENV=$NODE_ENV"
      - "BASE_URL=$API_BASE_URL"
      - "STRAPI_ADMIN_BACKEND_URL=$API_BASE_URL"
      - "NEKO_ROOMS_TRAEFIK_DOMAIN"
      - "NEKO_ROOMS_TRAEFIK_ROOMS_DOMAIN"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.codx-api.rule=Host(`$API_DOMAIN`)"
      - "traefik.http.routers.codx-api.entrypoints=${NEKO_ROOMS_TRAEFIK_ENTRYPOINT}"
      - "traefik.http.routers.codx-api.tls.certresolver=${NEKO_ROOMS_TRAEFIK_CERTRESOLVER}"
      - "traefik.http.routers.codx-api.service=codx-api"
      - "traefik.http.services.codx-api.loadbalancer.server.port=1337"

  web:
    image: node:16
    container_name: codx-web
    working_dir: /src
    command: bash -c "yarn && yarn serve"
    volumes:
      - "$CODX_PATH/client:/src"
    restart: unless-stopped
    environment:
      - "NODE_ENV=$NODE_ENV"
      - "BASE_URL=$WEB_BASE_URL"
      - "VUE_APP_API=$API_BASE_URL"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.codx-web.rule=Host(`$WEB_DOMAIN`)"
      - "traefik.http.routers.codx-web.entrypoints=${NEKO_ROOMS_TRAEFIK_ENTRYPOINT}"
      - "traefik.http.routers.codx-web.tls.certresolver=${NEKO_ROOMS_TRAEFIK_CERTRESOLVER}"
      - "traefik.http.routers.codx-web.service=codx-web"
      - "traefik.http.services.codx-web.loadbalancer.server.port=8080"

  neko-rooms:
    image: "codx/neko-rooms:latest"
    build:
      context: ../neko-rooms
    restart: "unless-stopped"
    environment:
      - "TZ"
      - "NEKO_ROOMS_EPR"
      - "NEKO_ROOMS_NAT1TO1"
      - "NEKO_ROOMS_TRAEFIK_DOMAIN=$NEKO_ROOMS_TRAEFIK_ROOMS_DOMAIN"
      - "NEKO_ROOMS_TRAEFIK_ENTRYPOINT"
      - "NEKO_ROOMS_TRAEFIK_CERTRESOLVER"
      - "NEKO_ROOMS_TRAEFIK_NETWORK"
      - "NEKO_ROOMS_TRAEFIK_CORS"
      - "NEKO_ROOMS_LOGS=true"
      - "NEKO_ROOMS_NEKO_IMAGES=$NEKO_ROOMS_NEKO_IMAGES"
      - "NEKO_ROOMS_DEBUG"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.neko-rooms-frontend.loadbalancer.server.port=8080"
      - "traefik.http.routers.neko-rooms.entrypoints=${NEKO_ROOMS_TRAEFIK_ENTRYPOINT}"
      - "traefik.http.routers.neko-rooms.rule=Host(`${NEKO_ROOMS_TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.neko-rooms.tls=true"
      - "traefik.http.routers.neko-rooms.tls.certresolver=${NEKO_ROOMS_TRAEFIK_CERTRESOLVER}"
      # IPWHITELIST
      - "traefik.http.middlewares.neko-rooms-ipwhitelist.ipwhitelist.sourcerange=${NEKO_ROOMS_IP_WHITELIST}"
      # MIDDLEWARES
      - "traefik.http.routers.neko-rooms.middlewares=neko-rooms-ipwhitelist"     
      

networks:
  default:
    external: true
    name: $NEKO_ROOMS_TRAEFIK_NETWORK