version: "3"
services:
  neko:
    image: "gbrian/neko"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
    environment:
      NEKO_SCREEN: 1920x1080@30
      NEKO_PASSWORD: ${NEKO_PASSWORD:-neko}
      NEKO_PASSWORD_ADMIN: ${NEKO_ADMIN_PASSWORD:-admin}
      NEKO_EPR: 52000-52100
      NEKO_ICELITE: 1
    restart: unless-stopped

  codx-coder:
    depends_on:
      - neko
    image: gbrian/coder
    user: $USER
    environment:
      - "PASSWORD=${PASSWORD:-coder}"
      - "GITHUB_USERNAME=$GITHUB_USERNAME"
    restart: unless-stopped